// Generated by CoffeeScript 1.4.0
(function() {
  var packages;

  packages = ['backbone', 'js/model_item'];

  define(packages, function(BB, Model) {
    var Collection;
    Collection = BB.Collection.extend({
      idAttribute: "_id",
      model: Model
    });
    return Collection;
  });

}).call(this);
