// Generated by CoffeeScript 1.4.0
(function() {
  var packages;

  packages = ['backbone', 'underscore', "text!view/index.html"];

  define(packages, function(BB, _, Tpl) {
    var View;
    return View = BB.View.extend({
      render: function() {
        this.$el.html(_.template(Tpl));
        return this;
      }
    });
  });

}).call(this);
