// Generated by CoffeeScript 1.4.0
(function() {
  var packages;

  packages = ["jquery", "underscore", "backbone", "js/item_row"];

  define(packages, function($, _, BB, Row) {
    var List;
    List = BB.View.extend({
      render: function() {
        var row;
        this.$el.empty();
        this.$el.attr('data-role', 'listview');
        this.$el.attr('data-theme', 'c');
        this.$el.attr('data-autodividers', "true");
        this.$el.attr('data-filter', "true");
        this.$el.attr('data-inset', "true");
        row = function(item) {
          return this.el.appendChild(new Row({
            model: item
          }).render().el);
        };
        return this.collection.forEach(row, this);
      }
    });
    return List;
  });

}).call(this);
