// Generated by CoffeeScript 1.4.0
(function() {
  var packages;

  packages = ["jquery", "underscore", "backbone", "text!view/item_view.html"];

  define(packages, function($, _, BB, Template) {
    var Page;
    Page = BB.View.extend({
      initialize: function() {
        return this.template = _.template(Template);
      },
      render: function() {
        this.$el.html(this.template(this.model.toJSON()));
        return this;
      }
    });
    return Page;
  });

}).call(this);
