// Generated by CoffeeScript 1.4.0
(function() {
  var packages;

  packages = ['backbone', 'jquery', 'underscore'];

  define(packages, function(BB, $, _) {
    var Row, template;
    template = _.template(['<a href= "#view/<%= _id %>">', '<%= name %>', '</a>'].join(''));
    Row = BB.View.extend({
      tagName: 'li',
      template: template,
      render: function() {
        this.el.innerHTML = this.template(this.model.toJSON());
        return this;
      }
    });
    return Row;
  });

}).call(this);
