// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    baseUrl: "/",
    paths: {
      text: "lib/text/text",
      domReady: "lib/domReady/domReady",
      jqm: "lib/jquery.mobile/jquery.mobile-1.2.0",
      jqmNavigator: "lib/jquery.mobile/jqmNavigator",
      backbone: "lib/backbone/backbone"
    },
    shim: {
      jqm: {
        deps: ["jquery", "jqmNavigator"]
      }
    }
  });

  require(["domReady", "js/router_item", "jqm"], function(domReady, Router) {
    /*
      # Created by Piotr Walczyszyn (@pwalczyszyn)
    
      # User: pwalczys
      # Date: 2/16/12
      # Time: 9:20 AM
    */
    return domReady(function() {
      var onDeviceReady;
      return onDeviceReady = function(desktop) {
        var router;
        if (desktop !== true) {
          cordova.exec(null, null, "SplashScreen", "hide", []);
        }
        $.mobile.pageContainer = $("#container");
        $.mobile.ajaxEnabled = false;
        $.mobile.linkBindingEnabled = false;
        $.mobile.hashListeningEnabled = false;
        $.mobile.pushStateEnabled = false;
        router = new Router();
        Backbone.history.start();
        $('div[data-role="page"]').live('pagehide', function(event, ui) {
          return $(event.currentTarget).remove();
        });
        return onDeviceReady(true);
      };
    });
  });

}).call(this);
