// Generated by CoffeeScript 1.4.0
(function() {
  var packages;

  packages = ['backbone'];

  define(packages, function(BB) {
    var Model;
    Model = BB.Model.extend({
      idAttribute: "_id",
      events: {
        'error': 'popup'
      },
      popup: function(err) {
        return console.log(err);
      },
      initialize: function() {},
      validate: function(attrs, options) {
        if (!attrs.name) {
          return 'No Name?';
        }
      }
    });
    return Model;
  });

}).call(this);
