// Generated by CoffeeScript 1.4.0
(function() {
  var packages;

  packages = ["jquery", "underscore", "backbone", 'js/item_list', "text!view/item_list.html"];

  define(packages, function($, _, BB, List, Template) {
    var Page;
    Page = BB.View.extend({
      initialize: function() {
        return this.template = _.template(Template);
      },
      render: function() {
        this.$el.html(this.template);
        this.listView = new List({
          collection: this.collection,
          el: $("ul", this.el)
        });
        this.listView.render();
        return this;
      }
    });
    return Page;
  });

}).call(this);
