// Generated by CoffeeScript 1.4.0
(function() {
  var items, packages;

  items = [
    {
      "_id": 1,
      name: 'test1'
    }, {
      "_id": 2,
      name: 'test2'
    }, {
      "_id": 3,
      name: 'test3'
    }, {
      "_id": 4,
      name: 'test4'
    }, {
      "_id": 5,
      name: 'test5'
    }
  ];

  packages = ["jquery", "backbone", 'js/collection_item', 'js/model_item', 'js/index', 'js/page', 'js/item_view', 'js/item_form'];

  define(packages, function($, BB, Collection, Model, Home, Page, View, Form) {
    var Router;
    Router = BB.Router.extend({
      routes: {
        "view/:id": "view",
        "new/": "addnew",
        "edit/:id": "form",
        "items/skip": "list",
        "items/": "list",
        "*all": "main"
      },
      initialize: function() {
        return this.collection = new Collection(items);
      },
      main: function() {
        return $.mobile.jqmNavigator.pushView(new Home);
      },
      list: function(skip) {
        return $.mobile.jqmNavigator.pushView(new Page({
          collection: this.collection
        }));
      },
      view: function(id) {
        return $.mobile.jqmNavigator.pushView(new View({
          model: this.collection.get(id)
        }));
      },
      form: function(id) {
        return $.mobile.jqmNavigator.pushView(new Form({
          model: this.collection.get(id)
        }));
      },
      addnew: function() {
        return $.mobile.jqmNavigator.pushView(new Form({
          collection: this.collection,
          urlBack: '#items/',
          urlSave: '#view/' + this.collection.length
        }));
      }
    });
    return Router;
  });

}).call(this);
